In [1]:
import numpy as np

In [2]:
#1D Array
arr_1d= np.array([1,2,3,4,5])

In [3]:
print(arr_1d)

[1 2 3 4 5]


In [4]:
x = np.array([1,2,3,4,5])

In [5]:
print(x)

[1 2 3 4 5]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
#2D Array
y =np.array([[1,2,3,4],[5,6,7,8]])
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
y.ndim

2

In [10]:
#3D Array
z=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
print(z)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
z.ndim

3

In [13]:
y.size

8

In [14]:
z.size

9

In [15]:
x.dtype

dtype('int32')

In [16]:
mx = np.ones((3,4))
print(mx)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
