# NumPy Functions 

In [1]:
 #(1)Arange()

In [4]:
import numpy as np

In [5]:
np.arange(1,13)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [7]:
#(2)Reshape()

In [11]:
x=np.array([1,2,3,4,5,6,7,8])
print(x)

[1 2 3 4 5 6 7 8]


In [13]:
y=x.reshape(2,4)

In [14]:
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [16]:
y=x.reshape(2,6)

In [17]:
print(y)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [18]:
y=x.reshape(3,4)

In [19]:
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
x=np.arange(1,13)

In [21]:
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
#To convert 2D to 3D 

In [27]:
z=y.reshape(2,3,2)

In [28]:
print(z)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
#(4)Ravel()=convert multi-Dimension to 1D

In [30]:
z.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
z.transpose()

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])