In [1]:
import numpy as np

In [2]:
x=np.arange(1,10).reshape(3,3)
y=np.arange(1,10).reshape(3,3)

In [3]:
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#(1) Addition of two matrix 
x+y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
#OR
np.add(x,y)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
#(2)Substraction of two matrix
x-y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
#OR
np.subtract(x,y)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
#(3) Multiplication of matrix(Elimentry multiplication )
x*y

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [12]:
#OR
np.multiply(x,y)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [13]:
#(4)Multiplication of two matrix(product of matrix)
x@y

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [15]:
#OR
x.dot(y)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [24]:
x=np.arange(1,21)

In [25]:
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [26]:
x.max()

20

In [29]:
x.argmax()

19

In [30]:
x.max(axis=0)

20

In [31]:
y=np.arange(1,17).reshape(4,4)
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [32]:
y.max(axis=0)

array([13, 14, 15, 16])

In [33]:
y.max(axis=1)

array([ 4,  8, 12, 16])

In [35]:
#To find the sum of matrix
np.sum(y)

136

In [36]:
np.sum(y,axis=0)

array([28, 32, 36, 40])

In [37]:
#To find std of matrix
y.std()

4.6097722286464435

In [38]:
y.mean()

8.5

In [39]:
#To find square root of all matrix element
np.sqrt(y)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [40]:
#To find exponent of all matrix element
np.exp(y)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06]])

In [41]:
np.log(y)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872]])

In [42]:
np.log10(y)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125],
       [1.11394335, 1.14612804, 1.17609126, 1.20411998]])